### ISSUE TITLE
Import Error: past.utils

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#268]
I'm getting an import error on:

    from past.utils import old_div

(`twitter/api.py` line 36). Assuming that's a missing file from a commit somewhere and the point is to do classic int division, is there a reason not to use `//`? The function is only used once on line 3742.

**Comment by jeremylow** [comment]
My apologies, I did not install the future module when requirements.txt was updated with the latest.

**Comment by bear** [comment]
np - glad this was resolved no matter which side of the fence it was resolved on :)

**Comment by tdk93** [comment]
Hey, I'm sorry if this is a stupid question but can you explain what you did to fix this error?
I'm getting the same error and I didn't really understand your comment about how you fixed it.

**Comment by bear** [comment]
@tdk93 honestly never a stupid question...

he added "future" to the requirements.txt file so it would be installed into any dev environment we create

see https://github.com/bear/python-twitter/blob/master/requirements.txt#L1

**Comment by jeremylow** [comment]
Sure, it's no problem at all. What you'll want to do is install the `future` package with pip, so
 
    pip install future

which provides the module `old`. If you want to be sure that you have everything required to use python-twitter, I'd suggest running 

    pip install -r requirements.txt

To make sure everything is installed and up to date with the package.

**Comment by tdk93** [comment]
Thanks for the response. I installed future package, but I still get the same error, namely something like this:
```
ERROR: Failure: ImportError (No module named past.utils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/akshay/New_Horizons/python-twitter/python-twitter/twitter/__init__.py", line 44, in <module>
    from .api import Api                        # noqa
  File "/home/akshay/New_Horizons/python-twitter/python-twitter/twitter/api.py", line 38, in <module>
    from past.utils import old_div
ImportError: No module named past.utils

```
Thanks.

**Comment by jeremylow** [comment]
Weird. I'm at work, but I'll see if I can replicate this evening. Are you
working in a virtual environment? It looks like no, but just to be sure.

**Comment by tdk93** [comment]
I was working in a virtual python environment but I had done pip install there. Shouldn't that have worked there? I mean isn't it a good practice to use virtual environment so it's dependencies remain confined to that particular environment.
Anyways I exited the environment and did `sudo pip install future` and everything worked, just had to install wraps and six packages too.
BTW Shouldn't these wraps and six packages also be added to the requirements.txt then?
Just respond whenever you can. Thanks a lot. Appreciate the help.

**Comment by bear** [comment]
the requirements.txt we are mentioning is for the development of python-twitter.

If your seeing issues because you are trying use python-twitter in your project, that means we need to add things to the setup.py so *your* `pip install python-twitter` will include the dependencies.

**Comment by tdk93** [comment]
I understand now. Thanks.
