### ISSUE TITLE
Application-only Authencation

### ISSUE THREAD

**Issue by WesleyJohnson** [bear/python-twitter#354]
Are there any plans to support app-only auth? I noticed the lib explicitly throws an error if you don't provide the access key and secret when instantiating, suggesting that Twitter requires this on all API calls, but it seems this may not be the case?

https://dev.twitter.com/oauth/application-only

**Comment by jeremylow** [comment]
Looking at the documentation, it doesn't seem too terrible, with the exception maybe of parsing new, possibly conflicting rate limits.

**Comment by bryanlandia** [comment]
I just created a new branch, feature/app-only-auth on my fork at https://github.com/bryanlandia/python-twitter/tree/feature/app-only-auth.
It's working, I'm getting the higher RateLimit through that api, but the changes have no test coverage yet so I wouldn't use in production.  Feel free to fork and contribute.

To use, just call Api with an additional optional parameter, `application_only_auth`.  It defaults to `False` if not passed, in which case you will use the normal User Auth API.

**Comment by bear** [comment]
@bryanlandia say the word and I'll add you as a contributor and we can get better visibility of your branch

**Comment by bryanlandia** [comment]
Mike

Sure, feel free to add me.

**Comment by bear** [comment]
done!

**Comment by WesleyJohnson** [comment]
Awesome, guys. I appreciate the work on this. I'll be keeping an eye out on this and hopefully be able to integrate on my next round of updates.

**Comment by jschultz** [comment]
Is there any movement on this issue? It seems the closest any widely used Python twitter client comes to supporting application only authentication and I'm keen to use it for real. With a little experimentation I managed to make it work . Still getting some warnings.

> /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py:281: DeprecationWarning: unicode for buf is no longer accepted, use bytes

Is it worth my while trying to work out this warning, tidying a few things up and making a pull request, or is this already in the pipeline?

**Comment by jeremylow** [comment]
@jschultz I think @bryanlandia has a pretty complete implementation at https://github.com/bryanlandia/python-twitter/commit/b6a427ac151c839ee2553d3dd81e051b4da900c7. I have nothing in the works, but I'm happy to contribute or write tests against that fork.

**Comment by jschultz** [comment]
OK thanks. I made some minor changes to @bryanlandia 's work and submitted a pull request. Still getting the deprecation warnings but suspect this is due to my local (Debian) installation and not a problem with python-twitter.

**Comment by jeremylow** [comment]
I saw that. Lets work on getting some tests in place before merging since it's a large change to the API.

**Comment by jschultz** [comment]
OK I'm trying to work out your testing environment. Never done this before so please excuse my stumbling. It seems that you need to provide consumer key and secret and access token through environment variables. So I'm not clear what it is able to do when I do `./setup.py test` - does it generate or retrieve some of these codes or does it just do the tests that are possible without them?

**Comment by bryanlandia** [comment]
Thanks for trying! I have not looked at this for a couple months. Been in school.  I probably wouldn't get to it for a few weeks still


Sent from my T-Mobile 4G LTE Device-------- Original message --------From: Jonathan <notifications@github.com> Date: 12/11/2016  3:32 AM  (GMT-05:00) To: bear/python-twitter <python-twitter@noreply.github.com> Cc: Bryan Wilson <bryanlandia@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [bear/python-twitter] Application-only Authencation (#354) 
Is there any movement on this issue? It seems the closest any widely used Python twitter client comes to supporting application only authentication and I'm keen to use it for real. With a little experimentation I managed to make it work . Still getting some warnings.

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py:281: DeprecationWarning: unicode for buf is no longer accepted, use bytes

Is it worth my while trying to work out this warning, tidying a few things up and making a pull request, or is this already in the pipeline?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bear/python-twitter","title":"bear/python-twitter","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bear/python-twitter"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jschultz in #354: Is there any movement on this issue? It seems the closest any widely used Python twitter client comes to supporting application only authentication and I'm keen to use it for real. With a little experimentation I managed to make it work . Still getting some warnings.\r\n\r\n\u003e /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py:281: DeprecationWarning: unicode for buf is no longer accepted, use bytes\r\n\r\nIs it worth my while trying to work out this warning, tidying a few things up and making a pull request, or is this already in the pipeline?"}],"action":{"name":"View Issue","url":"https://github.com/bear/python-twitter/issues/354#issuecomment-266269933"}}}

**Comment by jeremylow** [comment]
Lands with https://github.com/bear/python-twitter/pull/423
